// 包内文案 seam（提案 §6）：闭集 key + zh/en(/ja) 默认串——**机器抄自 WeebPaint src/i18n/strings.ts（2026-09-09，270 key）**，
// 宿主经 configureText(t) 接管（把这些 key 并进自己的 i18n SSoT）；宿主没实现的 key 落包内默认，不许裸英文占位。
// 别手改本表：重新抄 = 长跑计划里的脚本（家族根 tmp/gallery-keys → strings.ts 抽取）。
export type GalleryLang = "zh" | "en" | "ja";
export const GALLERY_TEXT = {
  "bk.andMore": { zh: "……等 {n} 件（全量名单在包内 backup-manifest.txt）", en: "…and {n} more (full list in backup-manifest.txt inside the zip)", ja: "…ほか {n} 件（全リストは zip 内の backup-manifest.txt）" },
  "bk.done": { zh: "已下载备份 {name}（{n} 件）", en: "Backup downloaded: {name} ({n} files)", ja: "バックアップをダウンロードしました：{name}（{n} 件）" },
  "bk.empty": { zh: "图库里没有可备份的文件", en: "Nothing in this gallery to back up", ja: "バックアップできるファイルがありません" },
  "bk.failed": { zh: "备份失败：{err}", en: "Backup failed: {err}", ja: "バックアップに失敗しました：{err}" },
  "bk.failedDetail": { zh: "取不到、不在本次备份里的 {n} 件（离线的纯云端件/锁定的加密件等）：", en: "{n} file(s) could NOT be read and are NOT in this backup (cloud-only while offline, locked encrypted, …):", ja: "取得できず今回のバックアップに含まれない {n} 件（オフラインのクラウド専用・ロック中の暗号化など）：" },
  "bk.failedN": { zh: "{n} 件未能取到（纯云端且离线？稍后重试）", en: "{n} files could not be read (cloud-only while offline? try again later)", ja: "{n} 件を取得できませんでした（クラウドのみ・オフライン？後で再試行してください）" },
  "bk.msg": { zh: "把这个图库里的全部文件打包成一个 zip 下载到本机。只读取，不改动图库。加密作品保持密文原样（备份里没有明文）。超过 {size} 的部分改为逐件下载。", en: "Packs every file in this gallery into one zip and downloads it. Read-only — the gallery is not modified. Encrypted artworks stay as ciphertext (no plaintext in the backup). Anything beyond {size} is downloaded file by file instead.", ja: "このギャラリーの全ファイルを 1 つの zip にまとめてダウンロードします。読み取りのみで、ギャラリーは変更しません。暗号化された作品は暗号文のまま（バックアップに平文は入りません）。{size} を超えた分は 1 ファイルずつダウンロードします。" },
  "bk.packing": { zh: "正在备份…（{done} / {total}）", en: "Backing up… ({done} / {total})", ja: "バックアップ中…（{done} / {total}）" },
  "bk.partialN": { zh: "{n} 个文件夹未能完整列举，备份可能不全", en: "{n} folders could not be listed in full — the backup may be incomplete", ja: "{n} 個のフォルダーを完全に一覧できませんでした。バックアップが不完全な可能性があります" },
  "bk.scanning": { zh: "正在清点图库…", en: "Scanning the gallery…", ja: "ギャラリーを確認中…" },
  "bk.scanningFolders": { zh: "正在清点图库…（已扫 {n} 个文件夹）", en: "Scanning the gallery… ({n} folders)", ja: "ギャラリーを確認中…（{n} フォルダー）" },
  "bk.spilled": { zh: "库太大，另有 {n} 件改为逐件下载", en: "Library too large — {n} more files downloaded individually", ja: "ライブラリが大きいため、他の {n} 件は個別にダウンロードしました" },
  "bk.spilledDetail": { zh: "超出 zip 预算、已改为逐件下载的 {n} 件（一件不丢，注意浏览器多文件下载确认）：", en: "{n} file(s) over the zip budget were delivered as individual downloads (nothing dropped — watch for the browser multi-download prompt):", ja: "zip 予算超過のため個別ダウンロードになった {n} 件（欠落なし。ブラウザの複数ダウンロード確認に注意）：" },
  "bk.title": { zh: "下载全库备份", en: "Download full backup", ja: "ライブラリ全体をバックアップ" },
  "bk.truncated": { zh: "文件夹太多，只扫到前 {n} 个，备份不全", en: "Too many folders — only the first {n} were scanned; the backup is incomplete", ja: "フォルダーが多すぎます。最初の {n} 個のみを走査しました。バックアップは不完全です" },
  "cf.act.cloudWins": { zh: "云端覆盖本地", en: "Cloud overwrites local", ja: "クラウドでローカルを上書き" },
  "cf.act.localWins": { zh: "本地覆盖云端", en: "Local overwrites cloud", ja: "ローカルでクラウドを上書き" },
  "cf.act.openLocal": { zh: "打开本地", en: "Open local", ja: "ローカルを開く" },
  "cf.body.open": { zh: "「{name}」本机还有未上传的改动。", en: "“{name}” has changes on this device that were not uploaded yet.", ja: "「{name}」にはまだアップロードしていない変更がこの端末にあります。" },
  "cf.body.push": { zh: "「{name}」在云端和本机各有一版新改动。", en: "“{name}” has new changes both in the cloud and on this device.", ja: "「{name}」はクラウドとこの端末の両方に新しい変更があります。" },
  "cf.checkingCloud": { zh: "检查云端", en: "Checking cloud", ja: "クラウドを確認中" },
  "cf.cloudAccountInfo": { zh: "云端：{who}", en: "Cloud: {who}", ja: "クラウド：{who}" },
  "cf.cloudAccountOfflineInfo": { zh: "云端：{who}（离线）", en: "Cloud: {who} (offline)", ja: "クラウド：{who}（オフライン）" },
  "cf.cloudAccountOfflineTitle": { zh: "云端：{who}（离线，无法推 / 拉）", en: "Cloud: {who} (offline, cannot push / pull)", ja: "クラウド：{who}（オフライン、push / pull 不可）" },
  "cf.cloudAccountTitle": { zh: "云端：{who}（点开账号菜单）", en: "Cloud: {who} (tap to open account menu)", ja: "クラウド：{who}（アカウントメニューを開く）" },
  "cf.cloudNewerTitle": { zh: "云端有新版本", en: "A newer version exists in the cloud", ja: "クラウドに新しいバージョンがあります" },
  "cf.cloudNotConfigured": { zh: "云端：未配置", en: "Cloud: not configured", ja: "クラウド：未設定" },
  "cf.cloudNotSignedIn": { zh: "云端：未登录", en: "Cloud: not signed in", ja: "クラウド：未ログイン" },
  "cf.cloudNotSignedInTitle": { zh: "云端：未登录（点开登录）", en: "Cloud: not signed in (tap to sign in)", ja: "クラウド：未ログイン（タップしてログイン）" },
  "cf.cloudOffline": { zh: "云端：离线", en: "Cloud: offline", ja: "クラウド：オフライン" },
  "cf.note.keptSafe": { zh: "被替换的版本会自动留底，不会丢失", en: "The replaced version is kept automatically — nothing is lost", ja: "置き換えられたバージョンは自動的に保管され、失われません" },
  "cf.signedIn": { zh: "已登录", en: "Signed in", ja: "ログイン済み" },
  "cf.skipToOffline": { zh: "跳过到离线", en: "Skip to offline", ja: "スキップしてオフライン" },
  "common.cancel": { zh: "取消", en: "Cancel", ja: "キャンセル" },
  "cp.downloadFailed": { zh: "拿不到 {name}（离线且本地无缓存？）", en: "Could not fetch {name} (offline with no local copy?)", ja: "{name} を取得できません（オフラインでローカルコピーなし？）" },
  "cp.downloading": { zh: "正在下载 {name}…", en: "Downloading {name}…", ja: "{name} をダウンロード中…" },
  "cp.importFailed": { zh: "云盘导入失败：{err}", en: "Cloud import failed: {err}", ja: "クラウドからの読み込みに失敗：{err}" },
  "enc.confirmMsg": { zh: "两次输入需一致", en: "Both entries must match", ja: "同じものを入力してください" },
  "enc.confirmTitle": { zh: "再输一遍确认", en: "Confirm password", ja: "もう一度入力して確認" },
  "enc.enterGalleryPw": { zh: "输入图库密码。密码只存在内存里，关页即忘。", en: "Enter the gallery password. It lives only in memory and is forgotten when the page closes.", ja: "ギャラリーのパスワードを入力。メモリにのみ保持され、ページを閉じると消えます。" },
  "enc.enterPwMsg": { zh: "图库已设过密码（跟账号走）。输入原密码；忘记 = 内容永久找不回。", en: "This gallery already has a password (tied to your account). Enter it — if forgotten, the content is permanently unrecoverable.", ja: "ギャラリーには既にパスワードが設定されています（アカウントに紐付き）。忘れた場合、内容は永久に復元できません。" },
  "enc.enterPwTitle": { zh: "输入图库密码", en: "Enter gallery password", ja: "ギャラリーパスワードを入力" },
  "enc.importPrompt": { zh: "这是加密文件。输入它的密码。", en: "This file is encrypted. Enter its password.", ja: "これは暗号化ファイルです。パスワードを入力してください。" },
  "enc.locked.aria": { zh: "已加密", en: "Encrypted", ja: "暗号化済み" },
  "enc.setPwMismatch": { zh: "两次输入不一致，重新设置", en: "Entries don't match — try again", ja: "入力が一致しません。やり直してください" },
  "enc.setPwMsg": { zh: "整个图库共用这一个密码。忘记 = 内容永久找不回（没有任何后门）；太短的密码可被暴力破解。加密文件用 7-Zip 输此密码也能打开。", en: "One password for the whole gallery. If forgotten, content is permanently unrecoverable (there is no backdoor); short passwords can be brute-forced. Encrypted files also open in 7-Zip with this password.", ja: "ギャラリー全体で1つのパスワードを共有します。忘れると内容は永久に復元できません（バックドアなし）。短いパスワードは総当たりに弱いです。暗号化ファイルは 7-Zip でも同じパスワードで開けます。" },
  "enc.setPwTitle": { zh: "设置图库密码", en: "Set gallery password", ja: "ギャラリーパスワードを設定" },
  "enc.unlockImportTitle": { zh: "解锁导入的加密文件", en: "Unlock imported encrypted file", ja: "インポートした暗号化ファイルのロック解除" },
  "enc.unlockTitle": { zh: "解锁加密作品", en: "Unlock encrypted artwork", ja: "暗号化作品のロック解除" },
  "enc.wrongRetry": { zh: "密码不对，再试一次", en: "Wrong password — try again", ja: "パスワードが違います。もう一度" },
  "err.cloudNetwork": { zh: "网络不通：暂时连不上云端。你的画都还在本地，稍后可重试。", en: "Network unreachable: could not reach the cloud. Your work is safe locally — try again later.", ja: "ネットワークに接続できません。作品はローカルに保存されています。後で再試行してください。" },
  "gal.busy.copy": { zh: "正在创建副本 {base}…", en: "Duplicating {base}…", ja: "複製中 {base}…" },
  "gal.busy.del": { zh: "正在删除 {name}…", en: "Deleting {name}…", ja: "削除中 {name}…" },
  "gal.busy.emptyTrash": { zh: "正在清空{label}回收站…", en: "Emptying {label} trash…", ja: "{label}のゴミ箱を空に…" },
  "gal.busy.move": { zh: "正在移动 {base} → {target}…", en: "Moving {base} → {target}…", ja: "移動中 {base} → {target}…" },
  "gal.busy.purge": { zh: "正在永久删除 {name}…", en: "Deleting {name} forever…", ja: "完全に削除中 {name}…" },
  "gal.busy.rename": { zh: "正在重命名 {name} → {to}…", en: "Renaming {name} → {to}…", ja: "名前変更中 {name} → {to}…" },
  "gal.busy.restore": { zh: "正在恢复 {name}…", en: "Restoring {name}…", ja: "復元中 {name}…" },
  "gal.busy.reupload": { zh: "重新上传中…", en: "Re-uploading…", ja: "再アップロード中…" },
  "gal.copy": { zh: "创建副本", en: "Duplicate", ja: "複製を作成" },
  "gal.del.activeSuffix": { zh: " 当前画布会关闭。", en: " The current canvas will close.", ja: " 現在のキャンバスは閉じられます。" },
  "gal.del.cloudDetail": { zh: "会进云端回收站，可恢复。", en: "Goes to cloud trash; can be restored.", ja: "クラウドのゴミ箱に入り、復元可能です。" },
  "gal.del.dirtyDetail": { zh: "本地有**未推送到云端的修改**，删除会丢这些改动。云端备份进回收站可恢复。", en: "Local has **unpushed changes**; deleting loses them. The cloud backup goes to trash and can be restored.", ja: "ローカルに**未送信の変更**があり、削除すると失われます。クラウドのバックアップはゴミ箱に入り復元可能です。" },
  "gal.del.imageDetail": { zh: "移到回收站（可恢复）。这是图片素材，不是画作。", en: "Move to trash (recoverable). This is an image file, not an artwork.", ja: "ゴミ箱へ移動（復元可）。これは画像ファイルで、作品ではありません。" },
  "gal.del.localDetail": { zh: "会进本地回收站，可恢复。", en: "Goes to local trash; can be restored.", ja: "ローカルのゴミ箱に入り、復元可能です。" },
  "gal.del.syncedDetail": { zh: "本地副本会一起删，云端进回收站可恢复。", en: "The local copy is deleted too; the cloud copy goes to trash and can be restored.", ja: "ローカルも削除され、クラウドはゴミ箱に入り復元可能です。" },
  "gal.delEmptyFolder": { zh: "删除空文件夹", en: "Delete empty folder", ja: "空のフォルダを削除" },
  "gal.delFolderNonEmpty": { zh: "删除（请先清空里面）", en: "Delete (empty it first)", ja: "削除（先に中を空に）" },
  "gal.deleted": { zh: "删除", en: "deleted", ja: "削除" },
  "gal.discardToTrash": { zh: "丢弃（送回收站）", en: "Discard (to trash)", ja: "破棄（ゴミ箱へ）" },
  "gal.divergedNote": { zh: "云端副本已被别的设备移动或删除；本地这份有未推送的修改。", en: "The cloud copy was moved or deleted by another device; this local copy has unpushed changes.", ja: "クラウド側は別端末で移動/削除されました。ローカルには未送信の変更があります。" },
  "gal.dlg.decryptMsg": { zh: "内容将以明文存放在本机与云端，任何能访问此设备或云账号的人都能查看。", en: "Contents will be stored as plaintext locally and in the cloud; anyone with access to this device or cloud account can view them.", ja: "内容はローカルとクラウドに平文で保存され、この端末やクラウドにアクセスできる人は誰でも閲覧できます。" },
  "gal.dlg.decryptTitle": { zh: "解除「{base}」的加密？", en: "Decrypt “{base}”?", ja: "「{base}」の暗号化を解除？" },
  "gal.dlg.delTitle": { zh: "删除 \"{name}\"？", en: "Delete “{name}”?", ja: "「{name}」を削除？" },
  "gal.dlg.emptyTrashMsg": { zh: "{label}回收站会被彻底清空，不可撤销。", en: "The {label} trash will be permanently emptied. Cannot be undone.", ja: "{label}のゴミ箱を完全に空にします。元に戻せません。" },
  "gal.dlg.emptyTrashTitle": { zh: "清空{label}回收站？", en: "Empty {label} trash?", ja: "{label}のゴミ箱を空に？" },
  "gal.dlg.moveMsg": { zh: "选择目标文件夹", en: "Choose target folder", ja: "移動先フォルダを選択" },
  "gal.dlg.moveTitle": { zh: "移动「{base}」到…", en: "Move “{base}” to…", ja: "「{base}」を移動…" },
  "gal.dlg.purgeMsg": { zh: "不可撤销。", en: "Cannot be undone.", ja: "元に戻せません。" },
  "gal.dlg.purgeTitle": { zh: "永久删除 \"{name}\"？", en: "Delete “{name}” forever?", ja: "「{name}」を完全に削除？" },
  "gal.dlg.rename": { zh: "重命名", en: "Rename", ja: "名前を変更" },
  "gal.dlg.renameNote": { zh: "重命名（{note}）", en: "Rename ({note})", ja: "名前を変更（{note}）" },
  "gal.empty.folder": { zh: "文件夹 \"{f}\" 是空的", en: "Folder “{f}” is empty", ja: "フォルダ「{f}」は空です" },
  "gal.empty.none": { zh: "还没有保存的作品。点右上加号新建一个，或先在 PC 上画一笔。", en: "No saved artwork yet. Tap + at top-right to create one, or draw on PC first.", ja: "保存された作品がありません。右上の＋で新規作成、またはPCで描いてください。" },
  "gal.empty.trash": { zh: "回收站是空的。", en: "Trash is empty.", ja: "ゴミ箱は空です。" },
  "gal.emptyFolder": { zh: "空文件夹", en: "Empty folder", ja: "空のフォルダ" },
  "gal.firstFrameFailed": { zh: "图库读取失败（详见诊断日志）", en: "Gallery listing failed (see the diagnostic log)", ja: "ギャラリーの読み込みに失敗しました（診断ログ参照）" },
  "gal.firstFrameTimeout": { zh: "图库读取超时：本地存储没有响应", en: "Gallery listing timed out: local storage did not respond", ja: "ギャラリーの読み込みがタイムアウトしました：ローカルストレージが応答しません" },
  "gal.folder": { zh: "文件夹", en: "Folder", ja: "フォルダ" },
  "gal.imageFile": { zh: "图片", en: "Image", ja: "画像" },
  "gal.loading": { zh: "加载中…", en: "Loading…", ja: "読み込み中…" },
  "gal.loc.cloud": { zh: "云端", en: "Cloud", ja: "クラウド" },
  "gal.loc.local": { zh: "本地", en: "Local", ja: "ローカル" },
  "gal.lockedThumb": { zh: "已加密 —— 点锁解锁预览", en: "Encrypted — tap lock to unlock preview", ja: "暗号化済み — ロックをタップしてプレビュー" },
  "gal.more": { zh: "更多操作", en: "More actions", ja: "その他の操作" },
  "gal.moveTo": { zh: "移动到…", en: "Move to…", ja: "移動…" },
  "gal.note.empty": { zh: "名字不能空", en: "Name can’t be empty", ja: "名前は空にできません" },
  "gal.note.fail": { zh: "失败：{e}", en: "Failed: {e}", ja: "失敗：{e}" },
  "gal.note.taken": { zh: "{loc}已有同名，换一个", en: "{loc} already has this name, pick another", ja: "{loc}に同名あり、別名に" },
  "gal.openDiag": { zh: "诊断日志", en: "Diagnostic log", ja: "診断ログ" },
  "gal.otherFile": { zh: "文件（在 WeebPaint 外管理）", en: "File (managed outside WeebPaint)", ja: "ファイル（WeebPaint 外で管理）" },
  "gal.ph.newName": { zh: "新名字", en: "New name", ja: "新しい名前" },
  "gal.pullLocal": { zh: "拉取到本地", en: "Pull to local", ja: "ローカルに取得" },
  "gal.purge": { zh: "永久删除", en: "Delete forever", ja: "完全に削除" },
  "gal.pushCloud": { zh: "推送到云端", en: "Push to cloud", ja: "クラウドに送信" },
  "gal.reload": { zh: "重新载入应用", en: "Reload app", ja: "アプリを再読み込み" },
  "gal.rename": { zh: "重命名", en: "Rename", ja: "名前を変更" },
  "gal.renameKeep": { zh: "重命名留存", en: "Rename & keep", ja: "名前を変えて保持" },
  "gal.restore": { zh: "恢复", en: "Restore", ja: "復元" },
  "gal.retry": { zh: "重试", en: "Retry", ja: "再試行" },
  "gal.reupload": { zh: "重新上传", en: "Re-upload", ja: "再アップロード" },
  "gal.root": { zh: "根目录", en: "root", ja: "ルート" },
  "gal.rootFolder": { zh: "/ 根目录", en: "/ root", ja: "/ ルート" },
  "gal.scope.both": { zh: "本地和云端", en: "local and cloud", ja: "ローカルとクラウド" },
  "gal.scope.cloud": { zh: "云端", en: "cloud", ja: "クラウド" },
  "gal.scope.local": { zh: "本地", en: "local", ja: "ローカル" },
  "gal.st.alreadyEnc": { zh: "已是加密作品", en: "Already encrypted", ja: "既に暗号化済みです" },
  "gal.st.alreadyInFolder": { zh: "已在该文件夹", en: "Already in that folder", ja: "既にそのフォルダ内です" },
  "gal.st.cancelled": { zh: "已取消", en: "Cancelled", ja: "キャンセルしました" },
  "gal.st.cancelledPw": { zh: "已取消（需要密码）", en: "Cancelled (password required)", ja: "キャンセル（パスワードが必要）" },
  "gal.st.cloudPullFirst": { zh: "纯云端作品先拉取到本地再{verb}", en: "Pull the cloud-only artwork to local first to {verb}", ja: "クラウドのみの作品は先にローカルへ取得してから{verb}" },
  "gal.st.copied": { zh: "已创建副本：{name}", en: "Duplicated: {name}", ja: "複製：{name}" },
  "gal.st.copyFail": { zh: "创建副本失败：{e}", en: "Duplicate failed: {e}", ja: "複製失敗：{e}" },
  "gal.st.copyNoBytes": { zh: "找不到源作品的字节，复制失败", en: "Source artwork bytes not found; duplicate failed", ja: "元作品のデータが見つからず複製失敗" },
  "gal.st.decryptFail": { zh: "解除加密失败：{e}", en: "Decryption failed: {e}", ja: "暗号化解除失敗：{e}" },
  "gal.st.decrypted": { zh: "已解除加密：{name}", en: "Decrypted: {name}", ja: "暗号化解除：{name}" },
  "gal.st.delCancelled": { zh: "已取消，没有删除「{name}」", en: "Cancelled — \"{name}\" was not deleted", ja: "キャンセルしました。「{name}」は削除していません" },
  "gal.st.delFail": { zh: "删除失败：{e}", en: "Delete failed: {e}", ja: "削除失敗：{e}" },
  "gal.st.delLocalOnly": { zh: "「{name}」已从本地移入回收站，但云端那份还在（离线或来历不明，没敢删）", en: "\"{name}\" was moved to the local recycle bin, but the cloud copy remains (offline or unknown lineage)", ja: "「{name}」をローカルのごみ箱に移動しましたが、クラウド側は残っています（オフラインまたは由来不明）" },
  "gal.st.delNothing": { zh: "「{name}」本地和云端都没有，无事可删", en: "\"{name}\" exists neither locally nor in the cloud — nothing to delete", ja: "「{name}」はローカルにもクラウドにも存在しません" },
  "gal.st.deleted": { zh: "已删除：{name}", en: "Deleted: {name}", ja: "削除：{name}" },
  "gal.st.emptyTrashCloudFail": { zh: "{n} 项云端没清（可能离线），回线再清", en: "{n} cloud item(s) not cleared (maybe offline); retry when online", ja: "{n} 件がクラウドで未削除（オフライン？）。オンライン復帰後に再試行" },
  "gal.st.emptyTrashCloudNeedLogin": { zh: "清空云端回收站需先登录并联网", en: "Emptying cloud trash requires sign-in and network", ja: "クラウドのゴミ箱を空にするにはサインインと接続が必要です" },
  "gal.st.emptyTrashDone": { zh: "已清空{label}回收站", en: "Emptied {label} trash", ja: "{label}のゴミ箱を空にしました" },
  "gal.st.emptyTrashPartial": { zh: "清空时部分失败", en: "Some items failed to clear", ja: "一部の削除に失敗しました" },
  "gal.st.encConflict": { zh: "云端有更新版本：{name} —— 本地已换、已标未推送；打开后按冲突流程处理", en: "Newer version in cloud: {name} — local swapped and marked unpushed; resolve conflict after opening", ja: "クラウドに新しい版：{name} — ローカルは変更・未送信済み。開いてから競合を解決" },
  "gal.st.encDeferred": { zh: "{okMsg}（本地完成；云端暂未跟上，已标未推送，回线后推送即同步）", en: "{okMsg} (local done; cloud not yet, marked unpushed; push when back online)", ja: "{okMsg}（ローカル完了；クラウド未追従、未送信。オンライン復帰後に送信で同期）" },
  "gal.st.encFail": { zh: "加密失败：{e}", en: "Encryption failed: {e}", ja: "暗号化失敗：{e}" },
  "gal.st.encNeedOnline": { zh: "已同步过云端的作品需在线操作（本地与云端要一起换）", en: "Cloud-synced artwork needs to be online (local and cloud swap together)", ja: "クラウド同期済みの作品はオンラインで操作（ローカルとクラウドを同時に）" },
  "gal.st.encryptedOk": { zh: "已加密：{name}（7-Zip 输此密码可恢复；忘记密码内容永久找不回）", en: "Encrypted: {name} (7-Zip with this password can recover; forgotten password = permanently lost)", ja: "暗号化：{name}（このパスワードで7-Zip復元可；忘れると内容は永久に失われます）" },
  "gal.st.folderDelFail": { zh: "删除文件夹失败：{e}", en: "Folder delete failed: {e}", ja: "フォルダ削除失敗：{e}" },
  "gal.st.folderDeleted": { zh: "已删除空文件夹：{name}", en: "Deleted empty folder: {name}", ja: "空のフォルダを削除：{name}" },
  "gal.st.moveFail": { zh: "移动失败：{e}", en: "Move failed: {e}", ja: "移動失敗：{e}" },
  "gal.st.moved": { zh: "已移动到：{target}", en: "Moved to: {target}", ja: "移動先：{target}" },
  "gal.st.nameTakenTarget": { zh: "{loc}目标已有同名「{base}」", en: "{loc} target already has “{base}”", ja: "{loc}の移動先に同名「{base}」あり" },
  "gal.st.nameUnchanged": { zh: "名字未变", en: "Name unchanged", ja: "名前は変わっていません" },
  "gal.st.noLocalBytes": { zh: "本地字节缺失", en: "Local bytes missing", ja: "ローカルデータがありません" },
  "gal.st.noOtherFolder": { zh: "没有别的文件夹可移（先新建一个）", en: "No other folder to move to (create one first)", ja: "移動先のフォルダがありません（先に作成）" },
  "gal.st.notEnc": { zh: "这不是加密作品", en: "This artwork isn’t encrypted", ja: "これは暗号化作品ではありません" },
  "gal.st.openActive": { zh: "这画正开着 —— 先退出到图库再{verb}", en: "This artwork is open — exit to gallery first to {verb}", ja: "この作品は開いています — 先にギャラリーに戻って{verb}" },
  "gal.st.purgeFail": { zh: "永久删除失败：{e}", en: "Permanent delete failed: {e}", ja: "完全削除失敗：{e}" },
  "gal.st.purged": { zh: "已永久删除：{name}", en: "Permanently deleted: {name}", ja: "完全に削除：{name}" },
  "gal.st.renamed": { zh: "已重命名：{to}", en: "Renamed: {to}", ja: "名前変更：{to}" },
  "gal.st.renamed2": { zh: "已重命名：{from} → {to}", en: "Renamed: {from} → {to}", ja: "名前変更：{from} → {to}" },
  "gal.st.restoreFail": { zh: "恢复失败：{e}", en: "Restore failed: {e}", ja: "復元失敗：{e}" },
  "gal.st.restored": { zh: "已恢复：{name}", en: "Restored: {name}", ja: "復元：{name}" },
  "gal.st.restoredRenamed": { zh: "已恢复：{name}（原名 {orig} 已被占用）", en: "Restored: {name} (original name {orig} was taken)", ja: "復元：{name}（元の名前 {orig} は使用中）" },
  "gal.st.reuploadConflict": { zh: "云端已存在同名文件，未覆盖：{name}（请改名或从云端拉取）", en: "A file with that name already exists on cloud; not overwritten: {name}", ja: "クラウドに同名ファイルが既に存在します。上書きしません：{name}" },
  "gal.st.reuploadFail": { zh: "重新上传失败：{e}", en: "Re-upload failed: {e}", ja: "再アップロード失敗：{e}" },
  "gal.st.reuploaded": { zh: "已重新上传：{name}", en: "Re-uploaded: {name}", ja: "再アップロード完了：{name}" },
  "gal.st.unlocked": { zh: "已解锁加密作品（密码只在内存，关页即忘）", en: "Unlocked (password kept in memory only, forgotten on close)", ja: "ロック解除（パスワードはメモリのみ、閉じると破棄）" },
  "gal.toTrash": { zh: "送到回收站", en: "Move to trash", ja: "ゴミ箱へ" },
  "gal.unloadLocal": { zh: "卸载本地", en: "Unload local", ja: "ローカルを解放" },
  "gal.verb.decrypt": { zh: "解除加密", en: "decrypt", ja: "暗号化解除" },
  "gal.verb.encrypt": { zh: "加密", en: "encrypt", ja: "暗号化" },
  "gc.redirectReadyMsg": { zh: "已保存到本机。接下来会跳到微软登录页，登录后自动回来。", en: "Saved on this device. Next you'll go to the Microsoft sign-in page and come back automatically.", ja: "この端末に保存しました。次に Microsoft のサインインページへ移動し、サインイン後に自動で戻ります。" },
  "gm.alreadyCurrent": { zh: "已经是当前图库", en: "Already the current gallery", ja: "すでに現在のギャラリーです" },
  "gm.backupDone": { zh: "已下载 {n} 份备份", en: "Downloaded {n} backups", ja: "バックアップを {n} 件ダウンロードしました" },
  "gm.closeDocFirst": { zh: "先关闭当前画，再切换或卸下图库", en: "Close the current painting before switching or detaching the gallery", ja: "ギャラリーを切り替える前に、現在の絵を閉じてください" },
  "gm.connectFolder": { zh: "连接本地文件夹…", en: "Connect local folder…", ja: "ローカルフォルダーを接続…" },
  "gm.connectOneDrive": { zh: "连接 OneDrive…", en: "Connect OneDrive…", ja: "OneDrive を接続…" },
  "gm.connectTitle": { zh: "连接图库", en: "Connect a gallery", ja: "ギャラリーを接続" },
  "gm.current": { zh: "当前图库：{label}（{src}）", en: "Current gallery: {label} ({src})", ja: "現在のギャラリー：{label}（{src}）" },
  "gm.dirtyAllPushed": { zh: "已全部上传，继续切换", en: "All uploaded — continuing", ja: "すべてアップロードしました。続行します" },
  "gm.dirtyBackup": { zh: "下载备份", en: "Download backups", ja: "バックアップをダウンロード" },
  "gm.dirtyForce": { zh: "仍要切换", en: "Switch anyway", ja: "それでも切り替える" },
  "gm.dirtyMsg": { zh: "切换后它们留在本机缓存，回到此图库时继续上传。注意：浏览器可能清除本机缓存，缓存不是保险箱——建议先下载备份。", en: "They stay in this device's cache and upload when you return. Note: the browser may evict local cache — it is not a safe. Consider downloading backups first.", ja: "この端末のキャッシュに残り、戻ったときにアップロードされます。注意：ブラウザはキャッシュを削除することがあります。先にバックアップのダウンロードをおすすめします。" },
  "gm.dirtyTitle": { zh: "有 {n} 张画未上云", en: "{n} paintings not yet uploaded", ja: "未アップロードの絵が {n} 枚あります" },
  "gm.disconnected": { zh: "已断开图库连接（画布与图库文件不受影响）", en: "Gallery disconnected (canvas and gallery files untouched)", ja: "ギャラリーの接続を解除しました（キャンバスとファイルはそのまま）" },
  "gm.dismiss": { zh: "关闭", en: "Dismiss", ja: "閉じる" },
  "gm.fileProtoCloudHelp": { zh: "单文件直接双击打开（file://）时，微软登录用不了——需要一个本地 http 环境。逃生舱：在这个文件所在的文件夹打开命令行，运行\n\n    python -m http.server 8000\n\n然后用浏览器打开 http://localhost:8000/{file} 再连接 OneDrive。（本地文件夹图库不受影响，可以直接用。）", en: "Opened directly from disk (file://), Microsoft sign-in cannot work — it needs a local http origin. Escape hatch: open a terminal in this file's folder and run\n\n    python -m http.server 8000\n\nthen open http://localhost:8000/{file} in your browser and connect OneDrive there. (Local folder galleries are unaffected.)", ja: "ファイルを直接開いた状態（file://）では Microsoft サインインは使えません——ローカル http 環境が必要です。このファイルのフォルダーでターミナルを開き、\n\n    python -m http.server 8000\n\nを実行し、ブラウザで http://localhost:8000/{file} を開いてから OneDrive に接続してください。（ローカルフォルダーのギャラリーはそのまま使えます。）" },
  "gm.forgetDirtyWarn": { zh: "⚠ 该图库还有 {n} 张画未上云（缓存留在本机，重新连接后可继续上传）。", en: "⚠ {n} paintings in that gallery are not yet uploaded (cache stays on this device; reconnect later to resume uploading).", ja: "⚠ そのギャラリーには未アップロードの絵が {n} 枚あります（キャッシュは端末に残り、再接続で再開できます）。" },
  "gm.forgetHint": { zh: "忘记（不动文件）", en: "Forget (files untouched)", ja: "一覧から削除（ファイルはそのまま）" },
  "gm.forgetMsg": { zh: "只从这台设备的名册移除，不动图库本身的文件。", en: "Removes it from this device's list only; gallery files are untouched.", ja: "この端末の一覧から削除するだけで、ギャラリーのファイルには触れません。" },
  "gm.forgetTitle": { zh: "忘记「{label}」？", en: "Forget \"{label}\"?", ja: "「{label}」を一覧から削除しますか？" },
  "gm.forgotten": { zh: "已忘记 {label}", en: "Forgot {label}", ja: "{label} を一覧から削除しました" },
  "gm.historyCaption": { zh: "最近连接过的：", en: "Recently connected:", ja: "最近接続したもの：" },
  "gm.offlineBanner": { zh: "图库「{label}」已离线——画照常，同步暂停", en: "Gallery \"{label}\" is offline — keep painting, sync paused", ja: "ギャラリー「{label}」はオフライン——描画は通常どおり、同期は一時停止" },
  "gm.offlineSuffix": { zh: " · 已离线", en: " · offline", ja: " · オフライン" },
  "gm.reconnect": { zh: "重新连接", en: "Reconnect", ja: "再接続" },
  "gm.reconnected": { zh: "已重新连接", en: "Reconnected", ja: "再接続しました" },
  "gm.seedFresh": { zh: "出厂全新", en: "Factory fresh", ja: "新規（デフォルト）" },
  "gm.seedInherit": { zh: "继承当前笔刷与设置", en: "Inherit current brushes & settings", ja: "現在のブラシと設定を引き継ぐ" },
  "gm.seedMsg": { zh: "「继承」拷贝一份当前笔刷与设置，此后各自独立；「出厂全新」从内置默认起步。", en: "\"Inherit\" copies your current brushes & settings (independent afterwards); \"factory fresh\" starts from built-in defaults.", ja: "「引き継ぐ」は現在のブラシと設定をコピー（以後は独立）。「新規」は内蔵デフォルトから始めます。" },
  "gm.seedTitle": { zh: "新图库的笔刷与设置", en: "Brushes & settings for the new gallery", ja: "新しいギャラリーのブラシと設定" },
  "gm.srcFolder": { zh: "本地文件夹", en: "Local folder", ja: "ローカルフォルダー" },
  "gm.srcOneDrive": { zh: "OneDrive", en: "OneDrive", ja: "OneDrive" },
  "gm.switchEntry": { zh: "切换图库…", en: "Switch gallery…", ja: "ギャラリーを切り替え…" },
  "gm.switched": { zh: "已切换到 {label}", en: "Switched to {label}", ja: "{label} に切り替えました" },
  "gm.transientAdopted": { zh: "已连接图库，这幅画已自动保存为「{name}」", en: "Gallery connected — this artwork was saved as \"{name}\"", ja: "ギャラリーに接続しました。この作品は「{name}」として保存されました" },
  "gs.changePwBusy": { zh: "正在更改密码 {n}/{total}…", en: "Changing password {n}/{total}…", ja: "パスワード変更中 {n}/{total}…" },
  "gs.changePwConfirmMsg": { zh: "本机有字节的加密作品会用新密码重封（云端只见密文）。云端未缓存、离线或失败的作品仍用旧密码，打开时会单独问。", en: "Encrypted artworks cached here are re-sealed with the new password (the cloud only ever sees ciphertext). Artworks not cached, offline, or failing stay on the old password and will ask for it when opened.", ja: "この端末にある暗号化作品を新しいパスワードで再封印します（クラウドには暗号文しか渡りません）。未キャッシュ・オフライン・失敗した作品は旧パスワードのままで、開くときに聞かれます。" },
  "gs.changePwConfirmTitle": { zh: "更改密码？", en: "Change password?", ja: "パスワードを変更しますか？" },
  "gs.changePwDone": { zh: "密码已更改：{n} 件已用新密码重封", en: "Password changed: {n} re-sealed", ja: "パスワードを変更しました：{n} 件を再封印" },
  "gs.changePwDoneKept": { zh: "密码已更改：{n} 件已重封，{m} 件仍用旧密码（{k} 个文件夹清单不完整）", en: "Password changed: {n} re-sealed, {m} still on the old password ({k} folders listed incompletely)", ja: "パスワードを変更：{n} 件を再封印、{m} 件は旧パスワードのまま（{k} フォルダは一覧が不完全）" },
  "gs.changePwNewMsg": { zh: "输入新密码。本机有字节的加密作品会逐件用新密码重封，不经明文。", en: "Enter the new password. Encrypted artworks cached on this device are re-sealed one by one, never through plaintext.", ja: "新しいパスワードを入力。この端末にある暗号化作品を、平文を経ずに順に再封印します。" },
  "gs.changePwNoVerifier": { zh: "还没设过图库密码；第一次加密作品时会设置。", en: "No gallery password yet — you set it when you first encrypt an artwork.", ja: "まだギャラリーのパスワードがありません。作品を初めて暗号化するときに設定します。" },
  "gs.changePwOldMsg": { zh: "先验证当前的图库密码。", en: "Verify the current gallery password first.", ja: "まず現在のギャラリーのパスワードを確認します。" },
  "gs.changePwOldTitle": { zh: "输入当前密码", en: "Enter current password", ja: "現在のパスワードを入力" },
  "gs.changePwSame": { zh: "新密码与当前密码相同，没有更改。", en: "Same as the current password — nothing changed.", ja: "現在のパスワードと同じです。変更はありません。" },
  "gs.changePwScanning": { zh: "正在清点加密作品…", en: "Listing encrypted artworks…", ja: "暗号化作品を確認中…" },
  "gs.clipboardNewFailed": { zh: "从剪切板新建失败：{err}", en: "Failed to create from clipboard: {err}", ja: "クリップボードからの新規作成に失敗しました：{err}" },
  "gs.clipboardNoImage": { zh: "剪贴板里没有图片", en: "No image in the clipboard", ja: "クリップボードに画像がありません" },
  "gs.cloudDisabledNoGallery": { zh: "云端功能已停用，图库不可用（可在设置里重新开启）", en: "Cloud features are disabled; the gallery is unavailable (re-enable in settings)", ja: "クラウド機能が無効のため、ギャラリーは利用できません（設定で再度有効化できます）" },
  "gs.created": { zh: "新建：{name}（{w}×{h}）", en: "Created: {name} ({w}×{h})", ja: "新規作成：{name}（{w}×{h}）" },
  "gs.createdTransient": { zh: "已新建画布 {w}×{h}（未保存·无家——保存时选择去处）", en: "New canvas {w}×{h} (unsaved, no home — choose where to save it later)", ja: "新しいキャンバス {w}×{h}（未保存・保存時に保存先を選択）" },
  "gs.creatingFolder": { zh: "正在创建文件夹 {name}…", en: "Creating folder {name}…", ja: "フォルダ {name} を作成中…" },
  "gs.folderCreateFailed": { zh: "建文件夹失败：{err}", en: "Failed to create folder: {err}", ja: "フォルダの作成に失敗しました：{err}" },
  "gs.folderCreated": { zh: "已建文件夹：{name}", en: "Folder created: {name}", ja: "フォルダを作成しました：{name}" },
  "gs.folderExists": { zh: "文件夹 \"{name}\" 已存在", en: "Folder \"{name}\" already exists", ja: "フォルダ「{name}」は既に存在します" },
  "gs.folderNameEmpty": { zh: "文件夹名不能空", en: "Folder name cannot be empty", ja: "フォルダ名を空にできません" },
  "gs.folderNameNoSlash": { zh: "文件夹名不能含 /（要建嵌套请进对应文件夹再点新建）", en: "Folder name cannot contain / (to nest, enter the target folder first, then create)", ja: "フォルダ名に / を含められません（入れ子を作るには対象フォルダに入ってから作成してください）" },
  "gs.folderNamePlaceholder": { zh: "文件夹名", en: "Folder name", ja: "フォルダ名" },
  "gs.folderNeedSignin": { zh: "图库离线（未登录或权限失效），无法新建文件夹", en: "Gallery is offline (not signed in / permission lost) — can't create a folder", ja: "ギャラリーがオフライン（未ログイン／権限切れ）のためフォルダを作成できません" },
  "gs.footUsage": { zh: "作品占用：{size}（{count} 件）", en: "Artwork usage: {size} ({count} items)", ja: "作品の使用量：{size}（{count} 件）" },
  "gs.footUsageTitle": { zh: "浏览器分配上限约 {size}；当前 {pct}% 已用（含 SW 缓存等）", en: "Browser allocation cap ~{size}; {pct}% used now (incl. SW cache, etc.)", ja: "ブラウザ割り当て上限は約 {size}；現在 {pct}% 使用中（SW キャッシュ等を含む）" },
  "gs.lockLabel": { zh: "锁定加密作品（忘掉密码）", en: "Lock encrypted works (forget password)", ja: "暗号化作品をロック（パスワードを破棄）" },
  "gs.locked": { zh: "已锁定加密作品（密码已从内存清除）", en: "Encrypted works locked (password cleared from memory)", ja: "暗号化作品をロックしました（パスワードをメモリから消去）" },
  "gs.newFolderDefault": { zh: "新文件夹", en: "New folder", ja: "新しいフォルダ" },
  "gs.newFolderTitle": { zh: "新建文件夹", en: "New folder", ja: "新しいフォルダ" },
  "gs.pwRecorded": { zh: "已记下密码（打开加密作品时验证）", en: "Password recorded (verified when opening an encrypted work)", ja: "パスワードを記録しました（暗号化作品を開くときに検証）" },
  "gs.pwResetDone": { zh: "已重置。下次加密时设置新密码", en: "Reset done. Set a new password next time you encrypt", ja: "リセットしました。次回の暗号化時に新パスワードを設定します" },
  "gs.pwWrongRetry": { zh: "密码不对，再试一次", en: "Wrong password, try again", ja: "パスワードが違います。もう一度" },
  "gs.quotaCritical": { zh: "本地存储 {pct}% 已满 — 立即去图库卸载不常用的作品", en: "Local storage {pct}% full — go to the gallery now and offload works you rarely use", ja: "ローカルストレージが {pct}% 使用済み — 今すぐギャラリーで使わない作品を退避してください" },
  "gs.quotaWarn": { zh: "本地存储 {pct}% 已用 — 建议在图库整理", en: "Local storage {pct}% used — consider tidying up in the gallery", ja: "ローカルストレージが {pct}% 使用済み — ギャラリーで整理することをおすすめします" },
  "gs.resetPwMsg": { zh: "重置后下次加密可设新密码；但已有加密作品仍是旧密码，无法用新密码解锁。确定重置？", en: "After reset you can set a new password for future encryption; existing encrypted works keep the old password and cannot be unlocked with the new one. Reset?", ja: "リセット後は新しいパスワードを設定できますが、既存の暗号化作品は旧パスワードのままです。リセットしますか？" },
  "gs.resetPwTitle": { zh: "重置图库密码？", en: "Reset gallery password?", ja: "ギャラリーパスワードをリセット？" },
  "gs.unlockLabel": { zh: "解锁加密作品…", en: "Unlock encrypted works…", ja: "暗号化作品のロック解除…" },
  "gs.unlockNoLocalMsg": { zh: "本地暂无加密作品可验证——密码先收下，用到时自动验证", en: "No local encrypted work to verify against — the password is saved for now and verified automatically when needed", ja: "ローカルに検証できる暗号化作品がありません——パスワードは先に保存し、使用時に自動で検証します" },
  "gs.unlockTitle": { zh: "解锁加密作品", en: "Unlock encrypted works", ja: "暗号化作品のロック解除" },
  "gs.unlockVerifierMsg": { zh: "输入图库密码（跟账号走）。忘记 = 内容永久找不回，没有后门", en: "Enter the gallery password (tied to your account). If forgotten, content is unrecoverable — there is no backdoor", ja: "ギャラリーのパスワードを入力（アカウントに紐づく）。忘れた場合、内容は復元できません" },
  "gs.unlocked": { zh: "已解锁加密作品（密码只在内存，关页即忘）", en: "Encrypted works unlocked (password stays in memory only, forgotten on page close)", ja: "暗号化作品のロックを解除しました（パスワードはメモリのみ、ページを閉じると消去）" },
  "gs.usageUnknown": { zh: "占用：未知", en: "Usage: unknown", ja: "使用量：不明" },
  "gs.usedSuffix": { zh: " · 已用 {pct}%", en: " · {pct}% used", ja: " · {pct}% 使用" },
  "gv.badge.cloudOnly": { zh: "纯云端（未拉到本地）", en: "Cloud only (not downloaded)", ja: "クラウドのみ（未ダウンロード）" },
  "gv.badge.conflictBoth": { zh: "云端与本机各有新改动 —— 打开或推送时会请你裁决", en: "New changes both in the cloud and on this device — you'll be asked to resolve on open or push", ja: "クラウドとこの端末の両方に新しい変更があります——開くかプッシュ時に選択を求められます" },
  "gv.badge.dirtyBoth": { zh: "本地+云端 · 本地有未推改动", en: "Local+cloud · unpushed local edits", ja: "ローカル+クラウド · 未プッシュの変更あり" },
  "gv.badge.float": { zh: "仅本地 · 有未上传的改动（从未同步）", en: "Local only · unsynced edits (never uploaded)" },
  "gv.badge.ghost": { zh: "云端副本已被移动或删除，本地有未推送的修改 —— 可「重命名留存」或「丢弃」", en: "Cloud copy was moved or deleted while local has unpushed edits — “rename & keep” or “discard”", ja: "クラウド側が移動/削除され、ローカルに未プッシュの変更があります——「改名して保持」か「破棄」を" },
  "gv.badge.localOnly": { zh: "仅本地（未上传云端）", en: "Local only (not uploaded)", ja: "ローカルのみ（未アップロード）" },
  "gv.badge.localPlain": { zh: "本地", en: "Local", ja: "ローカル" },
  "gv.badge.newerOnCloud": { zh: "云端有新版本 —— 打开会自动更新到云端版", en: "A newer version exists in the cloud — opening will update to it", ja: "クラウドに新しいバージョンがあります——開くと自動的に更新されます" },
  "gv.badge.pendingGone": { zh: "云端副本已消失，本地干净副本待处理 —— 可「重新上传」推回云端，或「删除」；宽限期后自动移入回收站", en: "Cloud copy is gone; clean local copy pending — “re-upload” to push it back, or “delete”; auto-trashed after the grace period", ja: "クラウド側が消失、ローカルのクリーンな複製が保留中——「再アップロード」か「削除」を。猶予期間後は自動でゴミ箱へ" },
  "gv.badge.syncedBoth": { zh: "本地+云端（已同步）", en: "Local+cloud (synced)", ja: "ローカル+クラウド（同期済み）" },
  "gv.rootDir": { zh: "/ 根目录", en: "/ Root", ja: "/ ルート" },
  "gv.src.both": { zh: "本地+云端", en: "Local+cloud", ja: "ローカル+クラウド" },
  "gv.src.cloud": { zh: "云端", en: "Cloud", ja: "クラウド" },
  "gv.src.cloudStillAlive": { zh: "{base}（云端仍在）", en: "{base} (still in cloud)", ja: "{base}（クラウドに残存）" },
  "gv.src.local": { zh: "本地", en: "Local", ja: "ローカル" },
  "gv.time.dayAgo": { zh: "{n} 天前", en: "{n} d ago", ja: "{n} 日前" },
  "gv.time.hourAgo": { zh: "{n} 小时前", en: "{n} h ago", ja: "{n} 時間前" },
  "gv.time.justNow": { zh: "刚刚", en: "Just now", ja: "たった今" },
  "gv.time.minAgo": { zh: "{n} 分钟前", en: "{n} min ago", ja: "{n} 分前" },
  "gv.time.unknown": { zh: "未知", en: "Unknown", ja: "不明" },
  "menu.decrypt": { zh: "解除加密…", en: "Decrypt…", ja: "暗号化を解除…" },
  "menu.encrypt": { zh: "加密保护…", en: "Encrypt…", ja: "暗号化…" },
  "name.copySuffix": { zh: "副本", en: "copy", ja: "コピー" },
  "nd.custom": { zh: "自定义…", en: "Custom…", ja: "カスタム…" },
  "save.signInLater": { zh: "暂不", en: "Not now", ja: "今はしない" },
  "save.signInNow": { zh: "登录", en: "Sign in", ja: "ログイン" },
  "save.signInPromptTitle": { zh: "已保存到本机", en: "Saved on this device", ja: "この端末に保存しました" },
} as const satisfies Record<string, Partial<Record<GalleryLang, string>>>;
export type GalleryTextKey = keyof typeof GALLERY_TEXT;
export type GalleryT = (key: GalleryTextKey, params?: Record<string, string | number>) => string;
let _lang: GalleryLang = "zh";
let _host: GalleryT | null = null;
function interpolate(s: string, params?: Record<string, string | number>): string {
  return params ? s.replace(/\{(\w+)\}/g, (m, k) => (k in params ? String(params[k]) : m)) : s;
}
/** 包内默认 t：按 lang 取，缺 → zh → key。 */
export const defaultT: GalleryT = (key, params) => {
  const e = GALLERY_TEXT[key] as Partial<Record<GalleryLang, string>> | undefined;
  return interpolate(e?.[_lang] ?? e?.zh ?? key, params);
};
/** 宿主接管文案（缺 key 时宿主返回 null/undefined/空串 → 落回默认）。 */
export function configureText(opts: { t?: (key: GalleryTextKey, params?: Record<string, string | number>) => string | null | undefined; lang?: GalleryLang }): void {
  if (opts.lang) _lang = opts.lang;
  if (opts.t) { const h = opts.t; _host = (k, p) => { const v = h(k, p); return v ? v : defaultT(k, p); }; }
}
export const t: GalleryT = (key, params) => (_host ?? defaultT)(key, params);
export const galleryTextKeys = (): GalleryTextKey[] => Object.keys(GALLERY_TEXT) as GalleryTextKey[];
